import { useEffect, useState, type ReactNode } from "react";
import { DEFAULT_APP_GENERAL, type AppGeneralConfig } from "@wlfv/shared";
import { api } from "@/lib/api";
import { SettingsSaveBar } from "@/components/settings/SettingsSaveBar";
import { useAutoSave } from "@/components/settings/useAutoSave";
import { Switch } from "@/components/ui/switch";
import { useT } from "@/lib/language";

function Toggle({
  title,
  hint,
  checked,
  onChange,
}: {
  title: string;
  hint: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <label className="flex items-start justify-between gap-4 py-4">
      <span>
        <span className="block text-[14px] font-medium">{title}</span>
        <span className="mt-1 block text-[13px] text-[var(--muted)]">{hint}</span>
      </span>
      <Switch checked={checked} onChange={onChange} label={title} />
    </label>
  );
}

function Field({
  title,
  hint,
  children,
}: {
  title: string;
  hint?: string;
  children: ReactNode;
}) {
  return (
    <label className="block py-3">
      <span className="block text-[13px] text-[var(--secondary)]">{title}</span>
      {children}
      {hint ? <span className="mt-1 block text-[12px] text-[var(--muted)]">{hint}</span> : null}
    </label>
  );
}

const inputClass = "mt-1 h-9 w-full rounded-lg bg-[var(--surface)] px-3 text-[13px] text-[var(--text)] outline-none";

export function AdminGeneralPanel({ onChange }: { onChange?: (config: AppGeneralConfig) => void }) {
  const tr = useT();
  const [config, setConfig] = useState<AppGeneralConfig>(DEFAULT_APP_GENERAL);
  const [ready, setReady] = useState(false);
  const { saving, status } = useAutoSave(config, ready, async (next) => {
    const saved = await api.send("/api/admin/general", "PATCH", next);
    onChange?.(saved.config as AppGeneralConfig);
  });

  useEffect(() => {
    api
      .get("/api/admin/general")
      .then((data) => setConfig(data.config as AppGeneralConfig))
      .catch(() => undefined)
      .finally(() => setReady(true));
  }, []);

  return (
    <div className="max-w-xl pr-8">
      <h2 className="text-[22px] font-medium">{tr("general")}</h2>
      <Field title={tr("responseWatermark")} hint={tr("responseWatermarkHint")}>
        <textarea
          className="mt-1 min-h-[72px] w-full rounded-lg bg-[var(--surface)] px-3 py-2 text-[13px] text-[var(--text)] outline-none"
          value={config.responseWatermark}
          placeholder="Generated by QV7"
          onChange={(event) => setConfig({ ...config, responseWatermark: event.target.value })}
        />
      </Field>
      <Field
        title={tr("webUiUrl")}
        hint={tr("webUiUrlHint")}
      >
        <input
          className={inputClass}
          value={config.webUiUrl}
          placeholder="https://chat.example.com"
          onChange={(event) => setConfig({ ...config, webUiUrl: event.target.value })}
        />
      </Field>
      <h3 className="mt-6 text-[15px] font-medium">{tr("userOptions")}</h3>
      <p className="mt-1 text-[13px] text-[var(--muted)]">{tr("userOptionsHint")}</p>
      <div className="mt-2 divide-y divide-[var(--border)]">
        <Toggle
          title={tr("sharing")}
          hint={tr("sharingHint")}
          checked={config.sharingEnabled}
          onChange={(sharingEnabled) => setConfig({ ...config, sharingEnabled })}
        />
        <Toggle
          title={tr("folders")}
          hint={tr("foldersHint")}
          checked={config.foldersEnabled}
          onChange={(foldersEnabled) => setConfig({ ...config, foldersEnabled })}
        />
        <Toggle
          title={tr("memories")}
          hint={tr("memoriesHint")}
          checked={config.memoriesEnabled}
          onChange={(memoriesEnabled) => setConfig({ ...config, memoriesEnabled })}
        />
      </div>
      <h3 className="mt-6 text-[15px] font-medium">{tr("userTools")}</h3>
      <p className="mt-1 text-[13px] text-[var(--muted)]">{tr("userToolsHint")}</p>
      <div className="mt-2 divide-y divide-[var(--border)]">
        <Toggle
          title={tr("webSearchChip")}
          hint={tr("toolWebSearchHint")}
          checked={config.toolWebSearch}
          onChange={(toolWebSearch) => setConfig({ ...config, toolWebSearch })}
        />
        <Toggle
          title={tr("codeInterpreter")}
          hint={tr("toolCodeHint")}
          checked={config.toolCode}
          onChange={(toolCode) => setConfig({ ...config, toolCode })}
        />
        <Toggle
          title={tr("canvas")}
          hint={tr("toolCanvasHint")}
          checked={config.toolCanvas}
          onChange={(toolCanvas) => setConfig({ ...config, toolCanvas })}
        />
        <Toggle
          title={tr("attachWebpage")}
          hint={tr("toolWebpageHint")}
          checked={config.toolWebpage}
          onChange={(toolWebpage) => setConfig({ ...config, toolWebpage })}
        />
        <Toggle
          title={tr("mcpTools")}
          hint={tr("toolMcpHint")}
          checked={config.toolMcp}
          onChange={(toolMcp) => setConfig({ ...config, toolMcp })}
        />
      </div>
      <Field title={tr("maxFolderCount")} hint={tr("maxFolderCountHint")}>
        <input
          type="number"
          min={0}
          max={500}
          className={inputClass}
          disabled={!config.foldersEnabled}
          value={config.maxFolderCount}
          onChange={(event) => setConfig({ ...config, maxFolderCount: Number(event.target.value) })}
        />
      </Field>
      <h3 className="mt-6 text-[15px] font-medium">{tr("tokenLimits")}</h3>
      <p className="mt-1 text-[13px] text-[var(--muted)]">{tr("tokenLimitsHint")}</p>
      <div className="mt-2 grid gap-3 sm:grid-cols-2">
        <Field title={tr("freeDayTokens")}>
          <input
            type="number"
            min={0}
            className={inputClass}
            value={config.freeDayTokens}
            onChange={(event) => setConfig({ ...config, freeDayTokens: Number(event.target.value) })}
          />
        </Field>
        <Field title={tr("freeWeekTokens")}>
          <input
            type="number"
            min={0}
            className={inputClass}
            value={config.freeWeekTokens}
            onChange={(event) => setConfig({ ...config, freeWeekTokens: Number(event.target.value) })}
          />
        </Field>
        <Field title={tr("proDayTokens")}>
          <input
            type="number"
            min={0}
            className={inputClass}
            value={config.proDayTokens}
            onChange={(event) => setConfig({ ...config, proDayTokens: Number(event.target.value) })}
          />
        </Field>
        <Field title={tr("proWeekTokens")}>
          <input
            type="number"
            min={0}
            className={inputClass}
            value={config.proWeekTokens}
            onChange={(event) => setConfig({ ...config, proWeekTokens: Number(event.target.value) })}
          />
        </Field>
      </div>
      <SettingsSaveBar saving={saving} status={status} />
    </div>
  );
}
